#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'componentsInGraph' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts 2D_INTEGER_ARRAY gb as parameter.
#

def componentsInGraph(gb):
    # Write your code here
    # Build graph
    graph = {}
    for l,r in gb:
        if l in graph: 
            graph[l].add(r)
        else: graph[l] = {r}
        if r in graph: 
            graph[r].add(l)
        else: graph[r] = {l}

# find all nodes in each cluster and count the number
# of nodes
    visited = set() 
    cluster = 0 # cluster index
    counter = [] # number of nodes in cluster
    for node in graph:
        if node not in visited:
# if its unvisited node, its a new cluster
            counter.append(0)
# find all nodes in this cluster start with current node
            stack = [node]
            while stack:
# get the next node in cluster
                n = stack.pop()
                if n not in visited:
                    counter[cluster] += 1
# mark node as visited
                    visited.add(n)
# add connected nodes to the stack
                    stack.extend(graph[n].difference(visited))
# if node was not visited, it is a new cluster
            cluster += 1
    return [min(counter), max(counter)]
  
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    gb = []

    for _ in range(n):
        gb.append(list(map(int, input().rstrip().split())))

    result = componentsInGraph(gb)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
