#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'getMax' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts STRING_ARRAY operations as parameter.
#

def getMax(operations):
    # Write your code here
    ansArr = []
    stack = []
    for s in operations:
        t = int(s[0])
        if t == 2:
            stack.pop()
        elif t == 1:
            n = int(s[2:])
            if stack and stack[-1] > n:
                stack.append(stack[-1])
            else:
                stack.append(n)
        else:
            ansArr.append(stack[-1])
    return ansArr
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    ops = []

    for _ in range(n):
        ops_item = input()
        ops.append(ops_item)

    res = getMax(ops)

    fptr.write('\n'.join(map(str, res)))
    fptr.write('\n')

    fptr.close()
