#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'solve' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def solve(arr):
    # Write your code here
    arr += [math.inf]
    A = [math.inf]
    s = 0
    
    i = 0
    while i < len(arr):
        
        if (e:= arr[i]) <= A[-1]:
            A.append(e)
            i += 1
            continue
        
        n = 0
        v = A[-1]
        while A[-1] == v:
            A.pop()
            n+=1
        s += math.perm(n, 2)
        
    return s

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr_count = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = solve(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
