#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'waiter' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts following parameters:
#  1. INTEGER_ARRAY number
#  2. INTEGER q
#

def waiter(number, q):
    # Write your code here
    answer = []
    
    point = 0
    index = 2
    
    while point < q:
        check = 0
        for now in range(1, index + 1):
            if index % now == 0:
                check += 1
            if now < index and check == 2:
                break
            if check == 2:
                point += 1
                
                A = []
                B = []
                
                for i in range(len(number)):
                    if number[i] % index == 0:
                        A.append(number[i])
                    else:
                        B.append(number[i])
                if point < q:
                    B.reverse()
                number = B
                answer.extend(A)
        index += 1
     
    answer.extend(number)
    return answer

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    q = int(first_multiple_input[1])

    number = list(map(int, input().rstrip().split()))

    result = waiter(number, q)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
